server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
spring:
    application:
      name: taskFlow
    jpa:
      generate-ddl: true
      show-sql: true
      hibernate:
            ddl-auto: create
    datasource:
        url: jdbc:postgresql://localhost:5432/taskflow
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
jwt:
    access:
        expirationInMs: 1440000 # 24 minutes
    refresh:
        expirationInMonths: 1
    signing:
        key: p5eHhtsr9qvSTaybbxGgYkhvnT7PYcqCxi6tNUEyXvQ=
logging:
  level:
    org:
      springframework:
        web: trace
